# frozen_string_literal: true

ruby '3.2.2'

source 'https://rubygems.org'

group :development do
  gem 'rubocop'
  gem 'rubocop-rspec', :require => false
end

group :test do
  gem 'rspec'
  gem 'json'
end
