version: 2
updates:
  # Maintain dependencies for poetry
  - package-ecosystem: 'pip'
    directory: '/python'
    schedule:
      interval: 'monthly'
    allow:
      - dependency-type: 'direct'
    open-pull-requests-limit: 0
