name: gurmukhi_utils
description: Utilities for Gurmukhi text.
version: 1.0.0
repository: https://github.com/ShabadOS/gurmukhi-utils/tree/main/dart

environment:
  sdk: ^3.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
