name: gurmukhi_utils
version: 0.1.0
description: Dart utilities library for converting, analyzing, and testing Gurmukhi strings.
repository: https://github.com/shabados/gurmukhi-utils
topics:
  - gurmukhi

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  path: ^1.8.3
