use gurmukhi::transcribe::{Script, transcribe};
use pretty_assertions::assert_eq;
use rstest::*;

// ─── LatinScholar (guru_latn) ───

#[rstest]
#[case("ੴ", "i˘k oa⸛kār")]
#[case("ਅਜ਼ਾਦ", "azād")]
#[case("ਕ਼", "qa")]
#[case("ਸਬਦ", "sabad")]
#[case("Example ਸਬਦ", "Example sabad")]
#[case("ਜਨਨੀ", "jananī")]
#[case("ਜਾਨ", "jān")]
#[case("ਸੁਤੁ", "sutu")]
#[case("ਕੁ", "ku")]
#[case("ਅਧਿਕ", "adhik")]
#[case("ਧਰਿ", "dhari")]
#[case("ਰਾਉ", "rāu")]
#[case("ਆਕਾਸ", "ākās")]
#[case("ਪੰਚ", "pa⸛c")]
#[case("ਬਤਊਆ", "bataūā")]
#[case("ਰਾਖੀਅਲੇ", "rākhīale")]
#[case("ਕਾਂਢੀਐ", "kā⸞ḍhīē")]
#[case("ਸਮਾਇ", "samāi")]
#[case("ਮਹਿੰਜਾ", "mahi⸛jā")]
#[case("ਤਊ", "taū")]
#[case("ਗਾਇਓ", "gāio")]
#[case("ਪੁਰਖਮਨੋਪਿਮੰ", "purakhamanopima⸛")]
#[case("ਆਦਿ", "ādi")]
#[case("ਪਰਕ੍ਰਿਤਿ", "parakʳiti")]
#[case("ਜਦਿਚਿੰਤਿ", "jadici⸛ti")]
#[case("ਨ", "na")]
#[case("ਤ੍ਵ", "tᵛa")]
#[case("ਸੰ", "sa⸛")]
#[case("ਭਇਅੰ", "bhaia⸛")]
#[case("ਪਰਾਭਯੰ", "parābhaya⸛")]
#[case("ਸ੍ਵਸਤਿ", "sᵛasati")]
#[case("ਸਮਬੵਿਅੰ", "samabʸia⸛")]
#[case("ਪ੍ਰਸੰਨਮਿਦੰ", "pʳasa⸛namida⸛")]
#[case("ਕਿੰ", "ki⸛")]
#[case("ਯਕ", "yak")]
#[case("ਬੇਐਬ", "beēb")]
#[case("ਮਮ", "mam")]
#[case("ਬਿਰਾਦਰਾਂ", "birādarā⸞")]
#[case("ਬਿਅਫਤਮ", "biaphatam")]
#[case("ਈਂ", "ī⸞")]
#[case("ਵਰ੍ਹਿਆ", "varʰiā")]
#[case("ਸੰਖੰ", "sa⸛kha⸛")]
#[case("ਅਸ੍ਚਰਜ", "asᶜaraj")]
#[case("ਬਿਸ੍ਟਾ", "bisᵗ̣ā")]
#[case("ਸਮਝ੍ਯੋ", "samajhay̶o")]
#[case("ਪੀਯ", "pīy")]
#[case("ਪ੍ਰਯਾਯੋ", "pʳayāyo")]
#[case("ਅਸ੍ਵਨ", "asᵛan")]
#[case("ਦਸ੍ਤਗੀਰੀ", "dasᵗagīrī")]
#[case("॥੧॥ ਰਹਾਉ ॥", "‖1‖ rahāu ‖")]
#[case("॥੨॥੫॥", "‖2‖5‖")]
#[case("ਮਹਲਾ ੫ ॥", "mahalā 5 ‖")]
#[case("ਸ੍ਨੇਹੰ", "sⁿeha⸛")]
#[case("ਸਤੵਿੰ", "satʸi⸛")]
#[case("ਦੁਖੵੰ", "dukhʸa⸛")]
#[case("ਹਤੵੰ", "hatʸa⸛")]
#[case("ਬਿਖੵਾਦੰ", "bikhʸāda⸛")]
#[case("ਆਇਆ", "āiā")]
#[case("ਜਗਦੀਸ੍ਵਰਹ", "jagadīsᵛarah")]
#[case("ਹੇ", "he")]
#[case("ਧਰਮ ਦ੍ਰਿੜੰਤਣਃ ॥", "dharam dʳiṛa⸛taṇẖ ‖")]
#[case("ਮਸਤਕਿ ਲਿਖੵਣਃ ॥੨੨॥", "masataki likhʸaṇẖ ‖22‖")]
#[case("ਯਯਾ", "yayā")]
#[case("ਸ਼ੇਰ", "sher")]
#[case("ਖ਼ਾਲਸਾ", "xālasā")]
#[case("ਗ਼ਰੀਬ", "ġarīb")]
#[case("ਲੋੁਭਾਨ", "loubhān")]
#[case("ਲੁੋਭਾਨ", "loubhān")]
#[case("ਜੀਅ", "jīa")]
#[case("ਲੋਅ", "loa")]
#[case("ਜੱਥਾ", "ja˘thā")]
#[case("ਵੱਡਾ", "va˘ḍā")]
#[case("ਮਿੱਟੀ", "mi˘ṭī")]
#[case("ਜਿਨੑਾ", "jin\u{0327}\u{0101}")]
#[case("ਬੰਨੑਿ", "ba\u{2e1b}n\u{0327}i")]
#[case("ਕਾਨੑੁ", "k\u{0101}n\u{0327}u")]
#[case("ਜਿੰਨੑੀ", "ji\u{2e1b}n\u{0327}\u{012b}")]
#[case("ਓਲੑਾ", "ol\u{0327}\u{0101}")]
#[case("ਸਾਮੑੈ", "s\u{0101}m\u{0327}\u{0113}")]
#[case("ਨ੍ਰਿੱਤੇ", "nʳi˘te")]
#[case("ਕ੍ਰੁੱਧ", "kʳu˘dh")]
#[case("ਜਿਨ੍ਹੈਂ", "jinʰē⸞")]
#[case("ਹ੍ਵੈੁਬੋ", "hᵛēubo")]
#[case("ਫ਼ਰੁੱਖ਼ੇ", "faru˘xe")]
#[case("ਥਿਤੀੰ", "thitī⸛")]
#[case("ਨੀੰਬਾ", "nī⸛bā")]
#[case("ਧ੍ਰੂਅ", "dhʳūa")]
#[case("ਆਲਿਸ੍ਯ", "ālisay̶")]
#[case("ਜ਼ੱਰਰਾ", "za˘rarā")]
#[case("ਚੜ੍ਹੂ", "caṛʰū")]
#[case("ਮੵਿਾਨੇ", "mʸiāne")]
#[case("ਧੵਿਾਵੈ", "dhʸiāvē")]
#[case("ਦ੍ਵਿਜ", "dᵛij")]
#[case("ਮਿਥੵੰਤ", "mithʸa⸛t")]
#[case("ਸੰਸਾਰਸੵ", "sa⸛sārasʸ")]
#[case("ਪ੍ਰਿਯ", "pʳiy")]
#[case("ਹਯਾੱਤਿ", "hayā˘ti")]
#[case("ਹਮਾਯੂੰ", "hamāyū⸛")]
#[case("ਭਯੋੁ", "bhayou")]
#[case("ਮਧ੍ਯ", "madhay̶")]
#[case("ਮਾਨ੍ਯੋ", "mānay̶o")]
#[case("ਭਿ੍ਯੋ", "bhiy̶o")]
#[case("ਕੀ੍ਯੋ", "kīy̶o")]
#[case("ਸ੍ਯਾਮ", "say̶ām")]
#[case("ਜ੍ਯੋਂ", "jay̶o⸞")]
#[case("ਨਾਮ︁ਯ", "nāmaƴ")]
#[case("ਸੁਨੀ︁ਯਹੁ", "sunīƴahu")]
#[case("ਸ︁ਯਾਮ", "saƴām")]
#[case("ਦਿਤ︁ਯਾਦਿਤ︀︁ਯ", "ditaƴāditaƴ̶")]
#[case("ਤ੍ਰਸ︀︁ਯੋ", "tʳasaƴ̶o")]
#[case("ਅੰਮ੍ਰਿਤਸਰ", "a⸛mʳitasar")]
#[case("ਪੰਜਾਬੀ", "pa⸛jābī")]
#[case("ਗੋਬਿੰਦ", "gobi⸛d")]
#[case("ਸੰਤ", "sa⸛t")]
#[case("ਨਾਨਕ", "nānak")]
#[case("ਵਾਹਿਗੁਰੂ", "vāhigurū")]
#[case("ਗੁਰਦੁਆਰਾ", "guraduārā")]
#[trace]
fn latin_scholar_test(#[case] input: String, #[case] expected: String) {
    assert_eq!(transcribe(input, Script::LatinScholar), expected);
}

// ─── Latin (guru_latn_pa) — assertions ───

#[rstest]
#[case("ੴ", "ikk oañkār")]
#[case("ਸਬਦ", "sabad")]
#[case("Example ਸਬਦ", "Example sabad")]
#[case("ਜਨਨੀ", "jananī")]
#[case("ਜਾਨ", "jān")]
#[case("ਸੁਤੁ", "sut")]
#[case("ਕੁ", "ku")]
#[case("ਅਧਿਕ", "adhik")]
#[case("ਧਰਿ", "dhar")]
#[case("ਰਾਉ", "rāu")]
#[case("ਆਕਾਸ", "ākās")]
#[case("ਪੰਚ", "pañc")]
#[case("ਬਤਊਆ", "bataūā")]
#[case("ਰਾਖੀਅਲੇ", "rākhīale")]
#[case("ਕਾਂਢੀਐ", "kāñḍhīē")]
#[case("ਸਮਾਇ", "samāi")]
#[case("ਤਊ", "taū")]
#[case("ਗਾਇਓ", "gāio")]
#[case("ਪੁਰਖਮਨੋਪਿਮੰ", "purakhamanopimañ")]
#[case("ਆਦਿ", "ād")]
#[case("ਪਰਕ੍ਰਿਤਿ", "parakrit")]
#[case("ਪਰ‧ਕ੍ਰਿਤਿ", "parkrit")]
#[case("ਜਦਿਚਿੰਤਿ", "jadiciñt")]
#[case("ਜਦਿ‧ਚਿੰਤਿ", "jadciñt")]
#[case("ਨ", "na")]
#[case("ਤ੍ਵ", "tva")]
#[case("ਸੰ", "sañ")]
#[case("ਭਇਅੰ", "bhaiañ")]
#[case("ਪਰਾਭਯੰ", "parābhayañ")]
#[case("ਸ੍ਵਸਤਿ", "svasat")]
#[case("ਸਮਬੵਿਅੰ", "samabyiañ")]
#[case("ਪ੍ਰਸੰਨਮਿਦੰ", "prasañnamidañ")]
#[case("ਕਿੰ", "kiñ")]
#[case("ਯਕ", "yak")]
#[case("ਬੇਐਬ", "beēb")]
#[case("ਮਮ", "mam")]
#[case("ਬਿਰਾਦਰਾਂ", "birādarāñ")]
#[case("ਬਿਅਫਤਮ", "biaphatam")]
#[case("ਈਂ", "īñ")]
#[case("ਵਰ੍ਹਿਆ", "varhiā")]
#[case("ਸੰਖੰ", "sañkhañ")]
#[case("ਅਸ੍ਚਰਜ", "ascaraj")]
#[case("ਬਿਸ੍ਟਾ", "bisṭā")]
#[case("ਸਮਝ੍ਯੋ", "samajhyo")]
#[case("ਸਮ‧ਝ੍ਯੋ", "samjhyo")]
#[case("ਪੀਯ", "pīy")]
#[case("ਪ੍ਰਯਾਯੋ", "prayāyo")]
#[case("ਅਸ੍ਵਨ", "asvan")]
#[case("ਦਸ੍ਤਗੀਰੀ", "dastagīrī")]
#[case("॥੧॥ ਰਹਾਉ ॥", "‖1‖ rahāu ‖")]
#[case("॥੨॥੫॥", "‖2‖5‖")]
#[case("ਸਤੵਿੰ", "satyañ")]
#[case("ਦੁਖੵੰ", "dukhyañ")]
#[case("ਹਤੵੰ", "hatyañ")]
#[case("ਬਿਖੵਾਦੰ", "bikhyādañ")]
#[case("ਆਇਆ", "āiā")]
#[case("ਹੇ", "he")]
#[case("ਧਰਮ ਦ੍ਰਿੜੰਤਣਃ ॥", "dharam driṛañtaṇẖ ‖")]
#[case("ਮਸਤਕਿ ਲਿਖੵਣਃ ॥੨੨॥", "masatak likhyaṇẖ ‖22‖")]
#[case("ਯਯਾ", "yayā")]
#[case("ਸ਼ੇਰ", "sher")]
#[case("ਖ਼ਾਲਸਾ", "ḳhālasā")]
#[case("ਖ਼ਾਲ‧ਸਾ", "ḳhālsā")]
#[case("ਗ਼ਰੀਬ", "ġarīb")]
#[case("ਲੋੁਭਾਨ", "lobhān")]
#[case("ਲੁੋਭਾਨ", "lobhān")]
#[case("ਜੀਅ", "jīa")]
#[case("ਲੋਅ", "loa")]
#[case("ਜੱਥਾ", "jatthā")]
#[case("ਵੱਡਾ", "vaḍḍā")]
#[case("ਮਿੱਟੀ", "miṭṭī")]
#[case("ਜਿਨੑਾ", "jinā")]
#[case("ਬੰਨੑਿ", "bañn")]
#[case("ਕਾਨੑੁ", "kān")]
#[case("ਜਿੰਨੑੀ", "jiñnī")]
#[case("ਓਲੑਾ", "olā")]
#[case("ਸਾਮੑੈ", "sāmē")]
#[case("ਨ੍ਰਿੱਤੇ", "nritte")]
#[case("ਕ੍ਰੁੱਧ", "kruddh")]
#[case("ਜਿਨ੍ਹੈਂ", "jinhēñ")]
#[case("ਹ੍ਵੈੁਬੋ", "hvēbo")]
#[case("ਫ਼ਰੁੱਖ਼ੇ", "faruḳḳhe")]
#[case("ਥਿਤੀੰ", "thitīñ")]
#[case("ਨੀੰਬਾ", "nīñbā")]
#[case("ਧ੍ਰੂਅ", "dhrūa")]
#[case("ਆਲਿਸ੍ਯ", "ālisya")]
#[case("ਜ਼ੱਰਰਾ", "zarrarā")]
#[case("ਚੜ੍ਹੂ", "caṛhū")]
#[case("ਮੵਿਾਨੇ", "myiāne")]
#[case("ਧੵਿਾਵੈ", "dhyiāvē")]
#[case("ਦ੍ਵਿਜ", "dvij")]
#[case("ਮਿਥੵੰਤ", "mithyañt")]
#[case("ਸੰਸਾਰਸੵ", "sañsārasy")]
#[case("ਪ੍ਰਿਯ", "priy")]
#[case("ਹਯਾੱਤਿ", "hayātt")]
#[case("ਹਮਾਯੂੰ", "hamāyūñ")]
#[case("ਭਯੋੁ", "bhayo")]
#[case("ਮਧ੍ਯ", "madhya")]
#[case("ਮਾਨ੍ਯੋ", "mānyo")]
#[case("ਭਿ੍ਯੋ", "bhiyo")]
#[case("ਕੀ੍ਯੋ", "kīyo")]
#[case("ਸ੍ਯਾਮ", "syām")]
#[case("ਸ︁ਯਾਮ", "sayām")]
#[case("ਜ੍ਯੋਂ", "jyoñ")]
#[case("ਨਾਮ︁ਯ", "nāmay")]
#[case("ਦਿਤ︁ਯਾਦਿਤ︀︁ਯ", "ditayāditya")]
#[case("ਤ੍ਰਸ︀︁ਯੋ", "trasyo")]
#[case("ਸ੍ਨੇਹੰ", "snehañ")]
#[case("ਖਿਨੁ", "khin")]
#[case("ਮੂਲਿ", "mūl")]
#[trace]
fn latin_assertions_test(#[case] input: String, #[case] expected: String) {
    assert_eq!(transcribe(input, Script::Latin), expected);
}

// ─── Latin — common phrases ───

#[rstest]
#[case("ਅੰਮ੍ਰਿਤਸਰ", "añmritasar")]
#[case("ਅੰਮ੍ਰਿਤ‧ਸਰ", "añmritsar")]
#[case("ਪੰਜਾਬੀ", "pañjābī")]
#[case("ਗੋਬਿੰਦ", "gobiñd")]
#[case("ਗੋੁਬਿੰਦ", "gobiñd")]
#[case("ਸੰਤ", "sañt")]
#[case("ਨਾਨਕ", "nānak")]
#[case("ਵਾਹਿਗੁਰੂ", "vāhigurū")]
#[case("ਵਾਹਿ‧ਗੁਰੂ", "vāhgurū")]
#[case("ਗੁਰਦੁਆਰਾ", "guraduārā")]
#[case("ਗੁਰ‧ਦੁਆਰਾ", "gurduārā")]
#[case(
    "ਵਾਹਿਗੁਰੂ ਜੀ ਕਾ ਖਾਲ‧ਸਾ ਵਾਹਿਗੁਰੂ ਜੀ ਕੀ ਫ਼ਤਿਹ",
    "vāhigurū jī kā khālsā vāhigurū jī kī fateh"
)]
#[case("ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ", "sat srī akāl")]
#[case("ਬੋਲੇ ਸੋ ਨਿਹਾਲ", "bole so nihāl")]
#[case("ਚੜ੍ਹਦੀ ਕਲਾ", "caṛhadī kalā")]
#[case("ਚੜ੍ਹ‧ਦੀ ਕਲਾ", "caṛhdī kalā")]
#[case("ਵੰਡ ਛਕੋ", "vañḍ chako")]
#[case("ਗੁਰਮਤਿ", "guramat")]
#[case("ਗੁਰ‧ਮਤਿ", "gurmat")]
#[case("ਪੰਜ ਪਿਆਰੇ", "pañj piāre")]
#[case("ਅਖੰਡ ਪਾਠ", "akhañḍ pāṭh")]
#[case("ਗੁਰੂ ਨਾਨਕ", "gurū nānak")]
#[case("ਗੁਰੂ ਅੰਗਦ", "gurū añgad")]
#[case("ਗੁਰੂ ਅਮਰ ਦਾਸ", "gurū amar dās")]
#[case("ਗੁਰੂ ਰਾਮ ਦਾਸ", "gurū rām dās")]
#[case("ਗੁਰੂ ਅਰ‧ਜਨ", "gurū arjan")]
#[case("ਗੁਰੂ ਹਰਿ‧ਗੋਬਿੰਦ", "gurū hargobiñd")]
#[case("ਗੁਰੂ ਹਰਿ ਗੋਬਿੰਦ", "gurū har gobiñd")]
#[case("ਗੁਰੂ ਹਰਿ ਰਾਇ", "gurū har rāi")]
#[case("ਗੁਰੂ ਹਰਿ ਕ੍ਰਿਸ਼ਨ", "gurū har krishan")]
#[case("ਗੁਰੂ ਤੇਗ਼ ਬਹਾਦਰ", "gurū teġ bahādar")]
#[case("ਗੁਰੂ ਗੋਬਿੰਦ ਸਿੰਘ", "gurū gobiñd siñgh")]
#[case("ਗੁਰੂ ਗ੍ਰੰਥ ਸਾਹਿਬ", "gurū grañth sāhib")]
#[case("ਭਗਤ ਬੈਣੀ", "bhagat bēṇī")]
#[case("ਭਾਈ ਮਰ‧ਦਾਨਾ", "bhāī mardānā")]
#[case("ਬਾਬਾ ਬੁੱਢਾ", "bābā buḍḍhā")]
#[case("ਬੇਨ‧ਤੀ", "bentī")]
#[case("ਅਰ‧ਦਾਸ", "ardās")]
#[case("ਤ੍ਵ ਪ੍ਰਸਾਦਿ ਸਵੱਯੇ", "tva prasād savayye")]
#[case("ਤ੍ਵ ਪ੍ਰਸਾਦਿ ਸ੍ਵਯੇ", "tva prasād svaye")]
#[trace]
fn latin_common_test(#[case] input: String, #[case] expected: String) {
    assert_eq!(transcribe(input, Script::Latin), expected);
}

// ─── Latin — haha rules ───

#[rstest]
#[case("ਰਹ‧ਰਾਸਿ ਸਾਹਿਬ", "rēhrās sāhib")]
#[case("ਸਹਜ", "sēhaj")]
#[case("ਮਹਲਾ ੫ ॥", "mēhalā 5 ‖")]
#[case("ਜਗਦੀਸ੍ਵਰਹ", "jagadīsvarēh")]
#[case("ਜਗ‧ਦੀਸ੍ਵਰਹ", "jagdīsvarēh")]
#[case("ਤਹ", "tēh")]
#[case("ਬਹਾਦਰ", "bahādar")]
#[case("ਰਹਾਉ", "rahāu")]
#[case("ਸਾਹਿਬ", "sāhib")]
#[case("ਅੱਲਾਹ", "allāh")]
#[case("ਫ਼ਤਿਹ", "fateh")]
#[case("ਧਰਹੁ", "dharōh")]
#[case("ਆਵਹੁ", "āvōh")]
#[case("ਓਹੁ", "oh")]
#[case("ਮੁਹਿ", "muh")]
#[case("ਜਾਣਾਇਹਿ", "jāṇāih")]
#[case("ਵਾਹਿ", "vāh")]
#[case("ਕਿਹੜਾ", "kehṛā")]
#[case("ਕਹਿਣਾ", "kēhṇā")]
#[case("ਸ਼ਹਿਰ", "shēhr")]
#[case("ਮਹਿੰਗਾ", "mēhñgā")]
#[case("ਵੀਸਰਹਿ", "vīsarēh")]
#[case("ਵੀਸ‧ਰਹਿ", "vīsrēh")]
#[case("ਆਵਹਿ", "āvēh")]
#[case("ਬੋਲਹਿ", "bolēh")]
#[case("ਦੁਹਰਾ", "dohrā")]
#[case("ਕੁਹੜਾ", "kohṛā")]
#[case("ਮੁਹੱਬਤ", "mohbbat")]
#[case("ਵਹੁਟੀ", "vōhṭī")]
#[case("ਮਨਹੁ", "manōh")]
#[case("ਇਹੁ", "ih")]
#[case("ਪਾਇਹੁ", "pāih")]
#[case("ਕਰਿਹੁ", "karih")]
#[case("ਸਦਿਹੁ", "sadih")]
#[case("ਸੁਣਿਅਹੁ", "suṇiōh")]
#[case("ਸੁਨੀ︁ਯਹੁ", "sunīyōh")]
#[case("ਸੁਆਲਿਹੁ", "suālih")]
#[case("ਸਿਵਰਿਹੁ", "sivarih")]
#[case("ਸਾਲਾਹਿਹੁ", "sālāhih")]
#[case("ਭੋਗਿਹੁ", "bhogih")]
#[case("ਮੇਲਿਹੁ", "melih")]
#[case("ਭਗਤਹੁ", "bhagatōh")]
#[case("ਨਿਹੰਗ", "nehñg")]
#[trace]
fn latin_haha_test(#[case] input: String, #[case] expected: String) {
    assert_eq!(transcribe(input, Script::Latin), expected);
}

// ─── Latin — dictionary words ───

#[rstest]
#[case("ਭਰਾ", "bharā")]
#[case("ਭਾਈ", "bhāī")]
#[case("ਮੋਤੀ", "motī")]
#[case("ਅਕਾਲੀ", "akālī")]
#[case("ਅਚਾਰ", "acār")]
#[case("ਅਜ਼ਾਦ", "azād")]
#[case("ਅਨਾਰ", "anār")]
#[case("ਰੱਬ", "rabb")]
#[case("ਅੱਖਰ", "akkhar")]
#[case("ਆਕਾਸ਼", "ākāsh")]
#[case("ਇਨਸਾਨ", "inasān")]
#[case("ਇਨ‧ਸਾਨ", "insān")]
#[case("ਇਸ਼ਕ", "ishak")]
#[case("ਇਸ਼ਕ਼", "ishaq")]
#[case("ਪਿਆਰ", "piār")]
#[case("ਉਸਤਤ", "usatat")]
#[case("ਉਸ‧ਤਤ", "ustat")]
#[case("ਉਸ‧ਤਾਦ", "ustād")]
#[case("ਕਣਕ", "kaṇak")]
#[case("ਕਮਲ", "kamal")]
#[case("ਪਦਮ", "padam")]
#[case("ਕੰਵਲ", "kañval")]
#[trace]
fn latin_dictionary_test(#[case] input: String, #[case] expected: String) {
    assert_eq!(transcribe(input, Script::Latin), expected);
}

// ─── Latin — vava/wawa words ───

#[rstest]
#[case("ਵੀਰ", "vīr")]
#[case("ਵੀਸ‧ਰਹਿ", "vīsrēh")]
#[case("ਅੱਚ‧ਵੀ", "accvī")]
#[case("ਵਿਆਹ", "viāh")]
#[case("ਵਿਚਾਰ", "vicār")]
#[case("ਵਿੱਚ", "vicc")]
#[case("ਵਿਛੋੜਾ", "vichoṛā")]
#[case("ਵਿਚੋਲਾ", "vicolā")]
#[case("ਵਿਦ‧ਯਾ", "vidyā")]
#[case("ਵਿਰ‧ਸਾ", "virsā")]
#[case("ਵਿਸਾਖੀ", "visākhī")]
#[case("ਵਿਸ‧ਰਨ", "visran")]
#[case("ਵਿਸ‧ਰਾਮ", "visrām")]
#[case("ਵੇਚ‧ਣਾ", "vecṇā")]
#[case("ਵੇਦ", "ved")]
#[case("ਵੇਕਾਰ", "vekār")]
#[case("ਵੇਲਾ", "velā")]
#[case("ਵੇਸਾਖੀ", "vesākhī")]
#[case("ਅਭੇਵ", "abhev")]
#[case("ਐਵੇਂ", "ēveñ")]
#[case("ਵੈਦ", "vēd")]
#[case("ਵੈਪਾਰੀ", "vēpārī")]
#[case("ਵੈਸਾਖੀ", "vēsākhī")]
#[case("ਵੈਸ਼‧ਨੋ", "vēshno")]
#[case("ਆਵਹਿ", "āvēh")]
#[case("ਵਛਾਈ", "vachāī")]
#[case("ਵਚੋਲਾ", "vacolā")]
#[case("ਵਦ", "vad")]
#[case("ਵੱਡਾ", "vaḍḍā")]
#[case("ਵਡਿਆਈ", "vaḍiāī")]
#[case("ਵਗ‧ਣਾ", "vagṇā")]
#[case("ਵਜਾਉਣਾ", "vajāuṇā")]
#[case("ਵਖ‧ਰਾ", "vakhrā")]
#[case("ਵਕੀਲ", "vakīl")]
#[case("ਵੰਡਨ", "vañḍan")]
#[case("ਵਨਜ", "vanaj")]
#[case("ਵਰ‧ਤਾਉਣਾ", "vartāuṇā")]
#[case("ਦੀਸ੍ਵਰ", "dīsvar")]
#[case("ਵਾਚਕ", "vācak")]
#[case("ਵਾਧੂ", "vādhū")]
#[case("ਵਾਹ", "vāh")]
#[case("ਵਾਕ", "vāk")]
#[case("ਵਾਲਾ", "vālā")]
#[case("ਵਾਰ", "vār")]
#[case("ਵਾਰਸ", "vāras")]
#[case("ਵਾਸ‧ਤੇ", "vāste")]
#[case("ਅਗ‧ਵਾਨ", "agvān")]
#[case("ਵੁਜੂ", "vujū")]
#[case("ਵੂਕ‧ਣੀ", "vūkṇī")]
#[case("ਵੋੜ੍ਹ", "voṛh")]
#[case("ਦਵੋਲੀਆ", "davolīā")]
#[case("ਵੌਕਾ", "vōkā")]
#[case("ਵਹੁਟੀ", "vōhṭī")]
#[case("ਪੀਵਹੁ", "pīvōh")]
#[trace]
fn latin_vava_test(#[case] input: String, #[case] expected: String) {
    assert_eq!(transcribe(input, Script::Latin), expected);
}

// ─── Devanagari (guru_deva) ───

#[rstest]
// Consonants
#[case("ਕ", "क")]
#[case("ਖ", "ख")]
#[case("ਗ", "ग")]
#[case("ਘ", "घ")]
#[case("ਚ", "च")]
#[case("ਜ", "ज")]
#[case("ਟ", "ट")]
#[case("ਡ", "ड")]
#[case("ਤ", "त")]
#[case("ਦ", "द")]
#[case("ਨ", "न")]
#[case("ਪ", "प")]
#[case("ਬ", "ब")]
#[case("ਮ", "म")]
#[case("ਯ", "य")]
#[case("ਰ", "र")]
#[case("ਲ", "ल")]
#[case("ਵ", "व")]
#[case("ਸ", "स")]
#[case("ਹ", "ह")]
// Vowels
#[case("ਅ", "अ")]
#[case("ਆ", "आ")]
#[case("ਇ", "इ")]
#[case("ਈ", "ई")]
#[case("ਉ", "उ")]
#[case("ਊ", "ऊ")]
#[case("ਏ", "ए")]
#[case("ਐ", "ऐ")]
#[case("ਓ", "ओ")]
#[case("ਔ", "औ")]
// Vowel signs
#[case("ਕਾ", "का")]
#[case("ਕਿ", "कि")]
#[case("ਕੀ", "की")]
#[case("ਕੁ", "कु")]
#[case("ਕੂ", "कू")]
#[case("ਕੇ", "के")]
#[case("ਕੈ", "कै")]
#[case("ਕੋ", "को")]
#[case("ਕੌ", "कौ")]
// Digits
#[case("੧੨੩", "१२३")]
#[case("੦੯", "०९")]
// Words
#[case("ਗੁਰੂ", "गुरू")]
#[case("ਸਿੰਘ", "सिंघ")]
#[case("ਨਾਨਕ", "नानक")]
#[case("ਵਾਹਿਗੁਰੂ", "वाहिगुरू")]
#[case("ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ", "सति स्री अकाल")]
// Special cases
#[case("ੴ", "ੴ")] // ik onkar: kept as-is
#[case("ੱ", "")] // adhak: dropped
#[case("ੰ", "ं")] // tippi → anusvara
#[case("ੵ", "्य")] // yakash → halant+ya
// Nukta consonants
#[case("ਸ਼ੇਰ", "शेर")]
#[case("ਖ਼ਾਲਸਾ", "\u{0959}\u{093e}\u{0932}\u{0938}\u{093e}")] // precomposed ख़ालसा
#[case("ਜ਼ਿੰਦਗੀ", "\u{095b}\u{093f}\u{0902}\u{0926}\u{0917}\u{0940}")] // precomposed ज़िंदगी
// Mixed text
#[case("Hello ਜੀ", "Hello जी")]
// Punctuation (shared between scripts)
#[case("।", "।")]
#[case("॥", "॥")]
#[trace]
fn devanagari_test(#[case] input: String, #[case] expected: String) {
    assert_eq!(transcribe(input, Script::Devanagari), expected);
}
