// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "gurmukhi.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNGurmukhiSpec.h"

@interface Gurmukhi : NSObject <NativeGurmukhiSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Gurmukhi : NSObject <RCTBridgeModule>
#endif

@end