const vishraams = Object.values( require( './vishraams' ) )

// Mappings
const shahmukhiMappings = {
  'ਖ਼ੁ': 'ِخو',
  ਖ਼ੁ: 'ِخو',
  '(?<![\u0A00-\u0A7F])ਉਹ': 'اوہ',
  '(?<![\u0A00-\u0A7F])ਆਏਗਾ(?![\u0A00-\u0A7F])': 'آۓگا',
  'ਆਏਗਾ(?![\u0A00-\u0A7F])': 'اۓگا',
  'ਾਏਗਾ(?![\u0A00-\u0A7F])': 'اۓگا',
  'ਏਗਾ(?![\u0A00-\u0A7F])': 'اےگا',
  '(?<![\u0A00-\u0A7F])ਛਾਂਗਾ(?![\u0A00-\u0A7F])': 'چھانگا',
  '(?<![\u0A00-\u0A7F])ਛਾਂਗੀ(?![\u0A00-\u0A7F])': 'چھانگی',
  '(?<![\u0A00-\u0A7F])ਢਾਂਗਾ(?![\u0A00-\u0A7F])': 'ڈھانگا',
  '(?<![\u0A00-\u0A7F])ਤਾਂਗਾ(?![\u0A00-\u0A7F])': 'تانگا',
  '(?<![\u0A00-\u0A7F])ਨਾਂਗਾ(?![\u0A00-\u0A7F])': 'نانگا',
  '(?<![\u0A00-\u0A7F])ਭਾਂਗਾ(?![\u0A00-\u0A7F])': 'بھانگا',
  '(?<![\u0A00-\u0A7F])ਲਾਂਗਾ(?![\u0A00-\u0A7F])': 'لانگا',
  '(?<![\u0A00-\u0A7F])ਬਾਂਗੇ(?![\u0A00-\u0A7F])': 'بانگے',
  '(?<![\u0A00-\u0A7F])ਬਝਲਾਂਗੇ(?![\u0A00-\u0A7F])': 'جھلانگے',
  '(?<![\u0A00-\u0A7F])ਇਕਾਂਗੀ(?![\u0A00-\u0A7F])': 'اِکانگی',
  '(?<![\u0A00-\u0A7F])ਸਾਂਗੀ(?![\u0A00-\u0A7F])': 'سانگی',
  '(?<![\u0A00-\u0A7F])ਝਾਂਗੀ(?![\u0A00-\u0A7F])': 'جھانگی',
  '(?<![\u0A00-\u0A7F])ਡਾਂਗੀ(?![\u0A00-\u0A7F])': 'ڈانگی',
  'ਾਂਗਾ(?![\u0A00-\u0A7F])': 'گا\u200cاں',
  '(?<![\u0A00-\u0A7F])ਆਏਗੀ(?![\u0A00-\u0A7F])': 'گاآۓ',
  'ਆਏਗੀ(?![\u0A00-\u0A7F])': 'اۓگی',
  'ਾਏਗੀ(?![\u0A00-\u0A7F])': 'اۓگی',
  'ਏਗੀ(?![\u0A00-\u0A7F])': 'اےگی',
  'ਾਂਗੀ(?![\u0A00-\u0A7F])': 'گی\u200cاں',
  '(?<![\u0A00-\u0A7F])ਆਏਗੇ(?![\u0A00-\u0A7F])': 'آۓگاے',
  'ਆਏਗੇ(?![\u0A00-\u0A7F])': 'اۓگاے',
  'ਾਏਗੇ(?![\u0A00-\u0A7F])': 'اۓگاے',
  'ਏਗੇ(?![\u0A00-\u0A7F])': 'اےگاے',
  'ਾਂਗੇ(?![\u0A00-\u0A7F])': 'گاے\u200cاں',
  '(?<![\u0A00-\u0A7F])ਆਏਗੀਆਂ(?![\u0A00-\u0A7F])': 'آۓگیاں',
  'ਆਏਗੀਆਂ(?![\u0A00-\u0A7F])': 'اۓگیاں',
  'ਾਏਗੀਆਂ(?![\u0A00-\u0A7F])': 'اۓگیاں',
  'ਏਗੀਆਂ(?![\u0A00-\u0A7F])': 'اےگیاں',
  'ਾਂਗੀਆਂ(?![\u0A00-\u0A7F])': 'گیاں\u200cاں',
  'ਊਂਗਾ(?![\u0A00-\u0A7F])': 'گا\u200cوں',
  'ਊਂਗੀ(?![\u0A00-\u0A7F])': 'گی\u200cوں',
  'ਊਂਗੇ(?![\u0A00-\u0A7F])': 'گاے\u200cوں',
  'ਊਂਗੀਆਂ(?![\u0A00-\u0A7F])': 'گیاں\u200cوں',
  '(?<![\u0A00-\u0A7F])ਇਆ': 'ای',
  '(?<![\u0A00-\u0A7F])ਇਉ': 'ایو',
  ਇਆ: 'يا',
  ਇ: 'ِا',
  '(?<![\u0A00-\u0A7F])ਆਈ': 'آئی',
  'ਆਈ': 'ائی',
  'ਾਈ': 'ائی',
  'ਿਓ': 'يو',
  'ਾਏ(?![\u0A00-\u0A7F])': 'اۓ',
  'ਾਏ': 'ائ',
  'ਾਓ': 'اؤ',
  'ਆਓ(?![\u0A00-\u0A7F])': 'اؤ',
  ਆਓ: 'آؤ',
  'ੰਪ': 'مپ',
  'ੰਨ': 'نّ',
  '(?<![\u0A00-\u0A7F])ਉ': 'اُ',
  ਉ: 'و',
  '(?<![\u0A00-\u0A7F])ਊ': 'اُو',
  ਊ: 'ؙو',
  ਈ: 'ای',
  ਏ: 'اے',
  'ਆ(?![\u0A00-\u0A7F])': 'ا',
  ਆ: 'آ',
  'ਐ(?![\u0A00-\u0A7F])': 'اَے',
  ਐ: 'اَی',
  ਔ: 'اَو',
  'ਆਂ(?![\u0A00-\u0A7F])': 'اں',
  ਆਂ: 'آن',
  ੴ: 'اک اونکار',
  '੍ਟ': 'ٹ',
  '੍ਨ': 'ن',
  '੍ਯ(?![\u0A00-\u0A7F])': 'ے',
  '੍ਯ': 'ی',
  '੍ਚ': 'چ',
  '੍ਤ': 'ت',
  'ੰ(?![\u0A00-\u0A7F])': 'ں',
  'ੰ': 'ن',
  '੍ਹ': 'ھ',
  'ਿ': 'ِ',
  'ੀ': 'ی',
  'ੁ': 'ُ',
  'ੂ': 'ُو',
  'ੇ(?![\u0A00-\u0A7F])': 'ے',
  'ੇ': 'ی',
  'ੈ(?![\u0A00-\u0A7F])': 'َے',
  'ੈ': 'َی',
  'ਂ(?![\u0A00-\u0A7F])': 'ں',
  'ਂ': 'ن',
  'ੋ': 'و',
  'ੌ': 'َو',
  '੍ਰ': 'ر',
  'ਾ': 'ا',
  'ੵ(?![\u0A00-\u0A7F])': 'ے',
  'ੵ': 'ی',
  'ੑ': 'ھ',
  'ੱ': 'ّ',
  '੍ਵ': 'و',
  'ਃ': ':',
  ਙ: 'نگ',
  ੳ: 'ا',
  ਅ: 'ا',
  ਬ: 'ب',
  ਭ: 'بھ',
  ਚ: 'چ',
  ਛ: 'چھ',
  ਦ: 'د',
  ਧ: 'دھ',
  ੲ: 'ا',
  ਓ: 'اَو',
  ਡ: 'ڈ',
  ਢ: 'ڈھ',
  'ਗ਼': 'غ',
  ਗ਼: 'غ',
  ਗ: 'گ',
  ਘ: 'گھ',
  ਹ: 'ہ',
  'ਜ਼': 'ز',
  ਜ਼: 'ز',
  ਜ: 'ج',
  ਝ: 'جھ',
  'ਕ਼': 'ق',
  ਕ: 'ک',
  'ਖ਼': 'خ',
  ਖ਼: 'خ',
  ਖ: 'کھ',
  'ਲ਼': 'ࣇ',
  ਲ਼: 'ࣇ',
  ਲ: 'ل',
  ਮ: 'م',
  ਨ: 'ن',
  ਪ: 'پ',
  'ਫ਼': 'ف',
  ਫ਼: 'ف',
  ਫ: 'پھ',
  ਤ: 'ت',
  ਥ: 'تھ',
  ਰ: 'ر',
  'ਸ਼': 'ش',
  ਸ: 'س',
  ਟ: 'ٹ',
  ਠ: 'ٹھ',
  ਵ: 'و',
  ੜ: 'ڑ',
  ਣ: 'ݨ',
  'ਯ(?![\u0A00-\u0A7F])': 'ے',
  ਯ: 'ی',
  ਞ: 'نج',
  '੧': '۱',
  '੨': '۲',
  '੩': '۳',
  '੪': '۴',
  '੫': '۵',
  '੬': '۶',
  '੭': '۷',
  '੮': '۸',
  '੯': '۹',
  '੦': '۰',
  '।': '۔',
  '॥': '۔۔',
  '.': '۔',
  ',': '،',
  ';': '؛',
  '-': ' ',
  '਼': '',
}

// Make each mapping an escaped global regex
const mappings = Object
  .entries( shahmukhiMappings )
  .map( ( [ exp, sub ] ) => [ new RegExp( exp.replace(/-/g, '\\x2d'), 'g' ), sub ] )

// Replacement rule to remove trailing ੁ and ਿ for pronunciation
// const replacements = [
//  [ new RegExp( `(\\S[^ਹ])([ਿੁ])([\\s$${vishraams.join( '' )}])`, 'ug' ), '$1$3' ], // Remove trailing ੁ and ਿ except when on ਹ or on a standalone akhar
// ]

const stress = [
  [ new RegExp( `ੱ([\u0A00-\u0A7F])`, 'ug' ), '$1ੱ' ], // Shift position of stress markers to after consonant to allow replacement for Shahmukhi
]

// Precompute the replacements and mappings
// const finalReplacements = [ ...stress, ...replacements, ...mappings ]
const finalReplacements = [ ...stress, ...mappings ]

/**
 * Transliterates Unicode Gurmukhi text to the Shahmukhi script.
 * @param {String} text The Unicode Gurmukhi text to convert.
 * @return {String} A Shahmukhi transliteration of the provided Unicode Gurmukhi string.
 * @example
 * toShahmukhi('ਹਮਾ ਸਾਇਲਿ ਲੁਤਫ਼ਿ ਹਕ ਪਰਵਰਸ਼ ॥') // => هما ساِال لُتف هک پرورش ۔۔
 * toShahmukhi('ਸੁ ਬੈਠਿ ਇਕੰਤ੍ਰ ॥੫੭੮॥') // => سُ بَےٹھ ِاکںتر ۔۔۵۷۸۔۔
 */
// const toShahmukhi = ( text ) => finalReplacements
//   .reduce( ( text, [ pre, exp, sub ] ) => text.replace( pre, exp, sub ), text )
const toShahmukhi = ( text ) => finalReplacements
  .reduce( ( text, [ pre, sub ] ) => text.replace( pre, sub ), text )

module.exports = toShahmukhi
