// Generated by uniffi-bindgen-react-native
#include "gurmukhi.h"
#include "generated/gurmukhi.hpp"

namespace gurmukhi {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeGurmukhi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}