name: Publish

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  crates-io:
    name: crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - uses: Swatinem/rust-cache@v2
      - run: mise run publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
